apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: cpo127-k0swc1-k0cp
  namespace: cpo127-k0swc1
spec:
  version: v1.27.2-k0s.0
  controllerPlaneFlags:
  - --enable-worker
  - --no-taints
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132
